#!/bin/bash

# 4 Knoten
#SBATCH -N 4

# 16 tasks
#SBATCH -n 16

# je 4 tasks/node
#SBATCH --ntasks-per-node 4

# Auf partition west
#SBATCH --partition=west

# Nach timescript.out schreiben
#SBATCH -o timescript.out

# ausführen
srun timescript

# "fertig" nach job_script.out schreiben
echo fertig > job_script.out
